name: crawl_tiktok

on:
  schedule:
    - cron:  '0 21 * * *'          # 毎朝6:00(JST)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Crawl Trending
        run: python fetch_trending.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: trending-json
          path: 'tiktok_*.json' 