name: crawl_tiktok

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test workflow
        run: |
          echo "TikTok Crawler Test"
          echo "Current date: $(date)"
          echo '{"test": "success", "timestamp": "'$(date)'"}' > test_result.json
      - name: Upload test result
        uses: actions/upload-artifact@v4
        with:
          name: test-result
          path: 'test_result.json'
