name: TikTok_Crawler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run TikTok crawler
        run: |
          python fetch_trending.py
          
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: tiktok-trending
          path: 'tiktok_*.json'
